### PR TITLE
Attempts to resolve issues created when two updates named the same with different dates causing HRESULT: 0x80240013

### LINKED ISSUE #131: Duplicate SQL Server Updates found when running escalated Windows Update script resulting in HRESULT: 0x80240013
I have noted on our regular builds that there is a strange issue occurs when I approve an update from the WSUS server, targeting SQL Server, that makes ghost duplicate updates appear (The ONLY difference, which I can see, is dates) see below. I can replicate this perfectly when I run the packer-windows-update-elevated.ps1 locally and logged into the system exact same system that outputted the below log. What's makes it even more confusing, if I run packer-windows-update.ps1 in the same machine (of course without running the packer-windows-update-elevated.ps1 first) it installs all updates fine and most importantly without any ghost updates. It ONLY appears if you run the packer-windows-update-elevated.ps1 script, which as we all know, creates a task in the context of the user and executes it.

vsphere-clone.<redacted>: Searching for Windows updates...
vsphere-clone.<redacted>: Found Windows update (2023-03-05; 465.15 MB): Security Update for SQL Server 2019 RTM GDR (KB5021125)
vsphere-clone.<redacted>: Found Windows update (2023-08-08; 56.6 MB): Windows Malicious Software Removal Tool x64 - v5.116 (KB890830)
vsphere-clone.<redacted>: **Found Windows update (2023-08-14; 751.04 MB): SQL Server 2019 RTM Cumulative Update (CU) 22 KB5027702**
vsphere-clone.<redacted>: Found Windows update (2023-03-24; 676.8 MB): SQL Server Management Studio 18.12.1
vsphere-clone.<redacted>: Found Windows update (2023-02-15; 741.62 MB): Security Update for SQL Server 2019 RTM CU (KB5021124)
vsphere-clone.<redacted>: **Found Windows update (2023-08-23; 751.04 MB): SQL Server 2019 RTM Cumulative Update (CU) 22 KB5027702**
vsphere-clone.<redacted>: Downloading Windows updates (6 updates; 3442.27 MB)...
vsphere-clone.<redacted>: ERROR: Exception from HRESULT: 0x80240013
vsphere-clone.<redacted>: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 231
vsphere-clone.<redacted>: ERROR: at <ScriptBlock>, <No file>: line 1
vsphere-clone.<redacted>: ERROR EXCEPTION: System.Runtime.InteropServices.COMException (0x80240013): Exception from HRESULT: 0x80240013
vsphere-clone.<redacted>: ERROR EXCEPTION:    at System.Management.Automation.ComInterop.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, ComMethodDesc method, Object[] args, UInt32 argErr)
vsphere-clone.<redacted>: ERROR EXCEPTION:    at CallSite.Target(Closure , CallSite , ComObject )
vsphere-clone.<redacted>: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
vsphere-clone.<redacted>: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
vsphere-clone.<redacted>: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
vsphere-clone.<redacted>: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

image

Packer Version - 1.9.1
Windows Update Plugin - 0.14.1

I have created a small behaviour patch for the Powershell script to try and stop it trying to install two. PR to follow!

** This is on a clean build, from scratch, every time **

### PR DESCRIPTION
**Pull request by stuartp44**
This PR detects when an update is attempted to be installed which equal the same update by its title. We do this by comparing what is currently in the install object, using the update title and skip the update it if we find it already in the object. This stops the HRESULT: 0x80240013 which is, as far as I know, when a duplicate update is attempted to be installed at the same time.

Resolves #131

### CODE REVIEW

**Comment by stuartp44** [comment]
See https://github.com/rgl/packer-plugin-windows-update/issues/131

**Comment by stuartp44** [comment]
May I ask for feedback for this? this PR genuinely fixes an issue we have using this and has no effect on dropping updates as they will be installed (if valid) on the next search. For us, on the next search the duplicate update is not there anyhow.

**Comment by stuartp44** [comment]
Is this able to be pushed into master now?

**Comment by rgl** [comment]
Am I sorry. But this is making too many style code changes; what are you using to reformat this?

Anyhow, please, limit the changes to just the part that has the change:

```
if (($updatesToInstall | Select-Object -ExpandProperty Title) -contains $updateTitle) {
...
```

**Comment by stuartp44** [comment]
Done and resolved the formatting. I use prettier, just had to disable it as it does it without having to save.

**Comment by stuartp44** [comment]
Chasing up on this? Are you happy with the changes?

**Pull request closed without merging**
