### PR TITLE
Update windows-update.ps1

### PR DESCRIPTION
**Pull request by TheSleepingFox**
adding try-catch for LastDeploymentChangeTime with default to todays date.

### CODE REVIEW

**Comment by TheSleepingFox** [comment]
This shoud hopefully fix Issue #144
Unfortunately I don't have access to an environment with 'make' currently, so unable to compile and confirm.

**Comment by rgl** [comment]
The stack trace from #144 points to https://github.com/rgl/packer-plugin-windows-update/blob/v0.16.0/update/windows-update.ps1#L190 but why is that `LastDeploymentChangeTime` `$null` at all?

Using the current date does not seem appropriate, as it varies. Using a static 1970-01-01 would be more appropriate to signal that something is odd with the date. Or even, make it `$null` or `unknown`.

**Comment by TheSleepingFox** [comment]
I hadn't looked through the rest of your script to see where it is used. So
didn't want to pass through as $null and potentially hit other $null value
exceptions. Linux Epoch time works. Unless you're filtering to only recent
patches to avoid showing Ancient stuff.

**Comment by markusheiliger** [comment]
To me it looks like the LastDeploymentChangeTime is only accessed to generate the update summary output. So moving on with the NULL value is maybe no dealbreaker (its just the output that looks a little bit strange). Especially for those folks (including me) who love and rely on this plugin as part of their image factory.

**Comment by jbne** [comment]
Do we know if $update could be null at that point as well? Doesn't seem like the likely culprit, but the stack trace doesn't give an indication on which is null.

**Comment by rgl** [comment]
`$update` or `$update.LastDeploymentChangeTime` being `$null` is quite strange. It seems something odd is happening elsewhere.

looking at the error in https://github.com/rgl/packer-plugin-windows-update/issues/144#issuecomment-2221084570, it seems to infer that KB5007651 has some kind of problem.

by any change have you guys tried to install that KB5007651 manually (e.g. from the windows update app)? did it work?

**Comment by rgl** [comment]
this was superseed with https://github.com/rgl/packer-plugin-windows-update/commit/27a4abb412c8ba6a67318d54794f41f201a549ec.

please try https://github.com/rgl/packer-plugin-windows-update/releases/tag/v0.16.1

**Pull request closed without merging**
